service: ts-serverless-starter
configValidationMode: error
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: ap-southeast-2
  versionFunctions: false

plugins:
  - serverless-offline
  - serverless-webpack

package:
  individually: true

functions:
  index:
    handler: src/index.handler
    events:
      - httpApi:
          path: /
          method: get
  
  list-buckets:
    handler: src/list-buckets.handler
    events:
      - httpApi:
          path: /list-buckets
          method: get
